### ISSUE TITLE
After update cheat doesn't working

### ISSUE THREAD

**Issue by ilt0r1** [sweeperxz/FullyExternalCS2#13]

**Comment by ilt0r1** [comment]
![image](https://github.com/sweeperxz/FullyExternalCS2/assets/163636371/e10ae318-4a3d-4a88-8f01-37ad4539390a)

**Comment by ilt0r1** [comment]
![Снимок экрана (559)](https://github.com/sweeperxz/FullyExternalCS2/assets/163636371/d67983ec-80e0-4be6-9f4b-62990c6f94c4)

**Comment by sweeperxz** [comment]
Was there any error message? Or is it still weighing an empty console? Try deleting offsets.json and restarting it.

**Comment by ilt0r1** [comment]
thanks, its working
