### ISSUE TITLE
Issues i found

### ISSUE THREAD

**Issue by 99119240** [sweeperxz/FullyExternalCS2#14]
Aimbot is broken most of the time.

Deathmatch is not accounted for.

Vis check = bad.

No UI!!!!
Use C# imgui.
IMgui.net
and clickabletransparentoverlay
USE NET 8.0!!!

**Comment by sweeperxz** [comment]
> Aimbot is broken most of the time.

tell me more about this

**Comment by 99119240** [comment]
Dude i try to shoot and it just puts my mouse point at air

**Comment by 99119240** [comment]
also provide .sln

**Comment by sweeperxz** [comment]
> Dude i try to shoot and it just puts my mouse point at air

you didn't let it calibrate, after starting, don't do anything with the mouse until you're flicked in different directions.

**Comment by sweeperxz** [comment]
> also provide .sln

Why? If there's a csproj

**Comment by 99119240** [comment]
mb

**Comment by 99119240** [comment]
also it says mouse cailbrate but break on  ffa
