### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ammystic** [sweeperxz/FullyExternalCS2#17]
i ran the exe with command prompt and my game opened and everything but nothing works like there is no esp and when i hold the keybinds it doenst do anything

**Comment by koleys** [comment]
Json file structure for 

        const string offsetsDw = "https://raw.githubusercontent.com/a2x/cs2-dumper/archive/offsets.json";
        const string offsetsClient = "https://raw.githubusercontent.com/a2x/cs2-dumper/archive/client.dll.json";

changed drastically.

**Comment by koleys** [comment]
> check if json file is created, if it is, delete it and run it again

This does not solve the issue as the code breaks due to JSON structure changes.

**Comment by sweeperxz** [comment]
> > check if json file is created, if it is, delete it and run it again
> 
> This does not solve the issue as the code breaks due to JSON structure changes.

a2x/cs2-dumper/ 
is not working now, so there is no way to update client.dll.json.

**Comment by sweeperxz** [comment]
https://github.com/sweeperxz/FullyExternalCS2/releases/tag/v1.7.1
