### ISSUE TITLE
Update to offset link

### ISSUE THREAD

**Issue by PokenDev21** [sweeperxz/FullyExternalCS2#24]
In the offset.cs this link

await FetchJson("https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client.dll.json"));

should be updated to this:
https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client_dll.json

the diffrence being the seperator for client_dll being a  _ instead of a  .

**Comment by b2a1eltos** [comment]
link dead

**Comment by sweeperxz** [comment]
fixed
