### ISSUE TITLE
Game process invalid

### ISSUE THREAD

**Issue by akeyr11alt** [sweeperxz/FullyExternalCS2#3]
When I type "dotnet run" it just starts printing "Game process invalid"
![faef](https://github.com/sweeperxz/FullyExternalCS2/assets/157230644/81c17acb-e010-4be8-9454-f800dd704f26)

**Comment by sweeperxz** [comment]
The message will appear if the game is minimized or not running, or in the worst case the game process is not detected. If you still see "Game process invalid" in the console, you can debug the code.
