### ISSUE TITLE
Hey nice Projekt

### ISSUE THREAD

**Issue by XrayShuvit** [sweeperxz/FullyExternalCS2#6]
it works only in window mode?

**Comment by vxnpp** [comment]
> Unfortunately yes, maybe it is possible to render in fullscreen mode, but I don't know how to do it yet.

maybe try to find out what phantomoverlay uses lol

**Comment by sweeperxz** [comment]
> > Unfortunately yes, maybe it is possible to render in fullscreen mode, but I don't know how to do it yet.
> 
> maybe try to find out what phantomoverlay uses lol

so go ahead and look for it)

**Comment by vxnpp** [comment]
> > > Unfortunately yes, maybe it is possible to render in fullscreen mode, but I don't know how to do it yet.
> > 
> > 
> > maybe try to find out what phantomoverlay uses lol
> 
> so go ahead and look for it)

or try this D3D11-Overlay-ImGui

**Comment by vxnpp** [comment]
> > > Unfortunately yes, maybe it is possible to render in fullscreen mode, but I don't know how to do it yet.
> > 
> > 
> > maybe try to find out what phantomoverlay uses lol
> 
> so go ahead and look for it)

maybe even this lol
https://www.unknowncheats.me/forum/4103779-post6.html

**Comment by vxnpp** [comment]
@sweeperxz

**Comment by saeedSDD** [comment]
Implementation problem
An error occurred: Response status code does not indicate success: 404 (Not Found).

**Comment by ZfpsGT1030** [comment]
i only want esp, can you make like neverlose chams i dont want vac

**Comment by SlyR-coder101** [comment]
why when i put aimbot , triggerbot or skeleton esp it dont work only esp and bomb timer , pls contact me on discord janz_back
