### ISSUE TITLE
Some questions regarding the work

### ISSUE THREAD

**Issue by GuCuh** [sweeperxz/FullyExternalCS2#8]
Hey! Cool project! I want to learn from a base and this seems to be a nice one, anyway, I'm not sure how to contact you so I will drop some questions here if you don't mind.

Would the aimbot work on fullscreen?
Being read-only, does that mean the chance of getting red trust is lower or reading will cause an instant red-trust?

Thank you for sharing your work!

**Comment by sweeperxz** [comment]
Would the aimbot work on fullscreen?

> Yes, aim will work in fullscreen mode, but everything related to drawing graphics will not work.

Being read-only, does that mean the chance of getting red trust is lower or reading will cause an instant red-trust?

> AimBot emulates the movement of your mouse, without interacting directly with the game memory. Red trust factor should not be, myself played on the account, on the trust factor did not affect. The maximum that you will get is a griefing ban.

I hope I've answered your questions.
